GET http://localhost:3001/
###

GET http://localhost:3001/info/
###

GET http://localhost:3001/api/persons/

###

GET http://localhost:3001/api/persons/5fc6b17e3e1db9fff892fa59/

###

PUT http://localhost:3001/api/persons/5fc29e11dda6ae68f7fe699e/
content-type: application/json

{
  "name": "Maxx", 
  "number": "586959655609"
}

###
      
DELETE http://localhost:3001/api/persons/5fcdfe00e8b29cd6e26d6a0d/

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
  "name": "Maxx", 
  "number": "39-23-6423122"
}